// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzCIJBoyLp4LHWAh2xd8N-H1e2YhGab3U',
    appId: '1:850882059025:web:da027a3e1f5009c0458ab0',
    messagingSenderId: '850882059025',
    projectId: 'sl-chat-f994c',
    authDomain: 'sl-chat-f994c.firebaseapp.com',
    storageBucket: 'sl-chat-f994c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCECBLqUDvSpzLJVRDQo2mUcXjL2Qv0-U',
    appId: '1:850882059025:android:afc089b9ec761cbf458ab0',
    messagingSenderId: '850882059025',
    projectId: 'sl-chat-f994c',
    storageBucket: 'sl-chat-f994c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzCIJBoyLp4LHWAh2xd8N-H1e2YhGab3U',
    appId: '1:850882059025:web:c923b93773c3132d458ab0',
    messagingSenderId: '850882059025',
    projectId: 'sl-chat-f994c',
    authDomain: 'sl-chat-f994c.firebaseapp.com',
    storageBucket: 'sl-chat-f994c.appspot.com',
  );
}
